name: run-tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v1

        - name: Cache dependencies
          uses: actions/cache@v1
          with:
            path: ~/.composer/cache/files
            key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

        - name: Setup PHP
            uses: shivammathur/setup-php@v1
            with:
              php-version: '7.4'
              extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
              coverage: none

        - name: Cache composer dependencies
          uses: actions/cache@v1
          with:
            path: vendor
            key: composer-${{ hashFiles('composer.lock') }}


        - name: Run composer install
            run: composer install -n --prefer-dist
            env:
              COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

        - name: Execute tests
          run: ./vendor/bin/phpunit
